services:
  db:
    image: postgres:17-alpine
    container_name: django_db
    volumes:
      - posgress_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"

  web:
    build: .
    # container_name: django_code
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    depends_on:
      - db
    env_file:
      - .env

volumes:
  posgress_data:
